=== MLB-LED-Scoreboard/mlb-led-scoreboard/schemas/coordinates/w128h32.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "128x32 Scoreboard Coordinates",
  "x-indent": "  ",
  "type": "object",
  "required": ["format"],
  "properties": {
    "x-schema": {
      "type": "string",
      "default": "./../schemas/coordinates/w128h32.schema.json",
      "readOnly": true,
      "x-enforceConst": true,
      "x-hidden": true
    },
    "format":       { "$ref": "./_common.schema.json#/$defs/format" },
    "defaults":     { "$ref": "./_common.schema.json#/$defs/defaults" },
    "bases":        { "$ref": "./_common.schema.json#/$defs/bases" },
    "final":        { "$ref": "./_common.schema.json#/$defs/final" },
    "inning":       { "$ref": "./_common.schema.json#/$defs/inning" },
    "outs":         { "$ref": "./_common.schema.json#/$defs/outs" },
    "atbat":        { "$ref": "./_common.schema.json#/$defs/atbat" },
    "batter_count": { "$ref": "./_common.schema.json#/$defs/batter_count" },
    "nohitter":     { "$ref": "./_common.schema.json#/$defs/nohitter" },
    "pregame":      { "$ref": "./_common.schema.json#/$defs/pregame" },
    "standings":    { "$ref": "./_common.schema.json#/$defs/standings" },
    "status":       { "$ref": "./_common.schema.json#/$defs/status" },
    "teams":        { "$ref": "./_common.schema.json#/$defs/teams" },
    "news":         { "$ref": "./_common.schema.json#/$defs/news" },
    "plugins":      { "$ref": "./_common.schema.json#/$defs/plugins" },
    "network":      { "$ref": "./_common.schema.json#/$defs/network" }
  },
  "default": {
    "x-schema": "./../schemas/coordinates/w128h32.schema.json",
    "format": 9.0,
    "defaults": {
      "font_name": "6x12"
    },
    "bases": {
      "1B": { "x": 88, "y": 9,  "size": 12 },
      "2B": { "x": 80, "y": 1,  "size": 12 },
      "3B": { "x": 72, "y": 9,  "size": 12 }
    },
    "final": {
      "inning":         { "x": 96,  "y": 14 },
      "scrolling_text": { "x": 0,   "y": 30, "width": 128 },
      "nohit_text":     { "x": 85,  "y": 22 }
    },
    "inning": {
      "break": {
        "number": { "x": 30, "y": 29 },
        "text":   { "x": 8,  "y": 29 },
        "due_up": {
          "due":     { "x": 77, "y": 8  },
          "up":      { "x": 98, "y": 8  },
          "divider": { "draw": true, "x": 64, "y_start": 0, "y_end": 64 },
          "loop":    128,
          "leadoff": { "x": 67, "y": 16, "width": 59 },
          "on_deck": { "x": 67, "y": 24, "width": 59 },
          "in_hole": { "x": 67, "y": 32, "width": 59 }
        }
      },
      "number": { "x": 128, "y": 8 },
      "arrow": {
        "size": 3,
        "up":   { "x_offset": -5, "y_offset": -4 },
        "down": { "x_offset": -5, "y_offset": -2 }
      }
    },
    "outs": {
      "1": { "x": 110, "y": 24, "size": 4, "nohit": { "x": 110, "y": 26, "size": 4 }, "perfect_game": { "x": 110, "y": 26, "size": 4 } },
      "2": { "x": 116, "y": 24, "size": 4, "nohit": { "x": 116, "y": 26, "size": 4 }, "perfect_game": { "x": 116, "y": 26, "size": 4 } },
      "3": { "x": 122, "y": 24, "size": 4, "nohit": { "x": 122, "y": 26, "size": 4 }, "perfect_game": { "x": 122, "y": 26, "size": 4 } }
    },
    "batter_count": {
      "x": 110, "y": 22,
      "nohit":        { "x": 110, "y": 16 },
      "perfect_game": { "x": 110, "y": 16 }
    },
    "nohitter": { "x": 110, "y": 24, "innings_until_display": 5 },
    "atbat": {
      "batter":      { "font_name": "5x8", "x": 52, "y": 30, "width": 40, "offset": 56 },
      "pitcher":     { "font_name": "5x8", "x": 1,  "y": 30, "width": 40 },
      "pitch":       { "font_name": "4x6", "x": 1,  "y": 50, "enabled": false, "mph": false, "desc_length": "short" },
      "pitch_count": { "font_name": "4x6", "x": 1,  "y": 50, "enabled": false, "append_pitcher_name": false },
      "loop": 64,
      "strikeout":   { "x": 60, "y": 30, "desc_length": "short", "enabled": true },
      "play_result": { "x": 60, "y": 30, "desc_length": "short", "enabled": true }
    },
    "pregame": {
      "scrolling_text": { "x": 0, "y": 30, "width": 128, "warmup": { "x": 0, "y": 30, "width": 128 } },
      "start_time":     { "x": 95, "y": 15 },
      "warmup_text":    { "x": 95, "y": 15 }
    },
    "standings": {
      "__comment__": "Delete this next line and make offset 8 to make the font much larger but only display 4 teams",
      "font_name": "4x6",
      "offset": 6,
      "height": 32,
      "width":  128,
      "divider":    { "x": 25 },
      "stat_title": { "x": 28 },
      "team": {
        "name":       { "x": 1   },
        "record":     { "x": 64  },
        "games_back": { "x": 126 }
      },
      "postseason": {
        "matchup_y_gap": 6,
        "series_x_gap":  16,
        "wc_x_start":    34,
        "wc_y_start":    6,
        "ds_a_y_start":  25,
        "__comment":     "all other coords are based off wild card position"
      }
    },
    "status": {
      "text":           { "x": 96, "y": 14, "short_text": false },
      "scrolling_text": { "x": 0,  "y": 30, "width": 128 }
    },
    "teams": {
      "background": {
        "away": { "width": 64, "height": 10, "x": 0, "y": 0  },
        "home": { "width": 64, "height": 10, "x": 0, "y": 10 }
      },
      "name": {
        "away": { "x": 4, "y": 8  },
        "home": { "x": 4, "y": 18 },
        "full": true
      },
      "accent": {
        "away": { "width": 2, "height": 10, "x": 0, "y": 0  },
        "home": { "width": 2, "height": 10, "x": 0, "y": 10 }
      },
      "record": {
        "enabled":  false,
        "position": "absolute",
        "away": { "font_name": "4x6", "x": 19, "y": 7  },
        "home": { "font_name": "4x6", "x": 19, "y": 17 },
        "hide_record_on_high_line_score": false
      },
      "line_score": {
        "away": { "x": 63, "y": 8  },
        "home": { "x": 63, "y": 18 },
        "show_hits_and_errors": false,
        "compress_digits": false,
        "shorten_team_name_on_high_line_score": true,
        "spacing": 3
      }
    },
    "news": {
      "scrolling_text": { "x": 0,   "y": 30, "width": 128 },
      "time":           { "x": 64,  "y": 9  },
      "conditions":     { "x": 100, "y": 22 },
      "temperature":    { "x": 10,  "y": 22 },
      "wind_speed":     { "x": 0,   "y": -2 },
      "wind_dir":       { "x": 0,   "y": -2 },
      "wind":           { "x": 40,  "y": 22 },
      "weather_icon":   { "x": 2,   "y": 1, "width": 15, "height": 15 }
    },
    "plugins": {},
    "network": {
      "font_name":  "4x6",
      "background": { "width": 7, "height": 7, "x": 121, "y": 25 },
      "text":       { "x": 125, "y": 31 }
    }
  }
}

=== MLB-LED-Scoreboard/mlb-led-scoreboard/coordinates/w64h32.example.json
{
  "$schema": "./../schemas/coordinates/w64h32.schema.json",
  "format": 9.0,
  "defaults": {
    "font_name": "4x6"
  },
  "bases": {
    "1B": {
      "x": 56,
      "y": 20,
      "size": 6
    },
    "2B": {
      "x": 51,
      "y": 15,
      "size": 6
    },
    "3B": {
      "x": 46,
      "y": 20,
      "size": 6
    }
  },
  "final": {
    "inning": {
      "x": 32,
      "y": 20
    },
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 64
    },
    "nohit_text": {
      "x": 1,
      "y": 20
    }
  },
  "inning": {
    "break": {
      "number": {
        "x": 2,
        "y": 29
      },
      "text": {
        "x": 2,
        "y": 22
      },
      "due_up": {
        "due": {
          "x": 18,
          "y": 22
        },
        "up": {
          "x": 18,
          "y": 28
        },
        "divider": {
          "draw": true,
          "x": 15,
          "y_start": 14,
          "y_end": 32
        },
        "loop": 64,
        "leadoff": {
          "x": 32,
          "y": 20,
          "width": 32
        },
        "on_deck": {
          "x": 32,
          "y": 26,
          "width": 32
        },
        "in_hole": {
          "x": 32,
          "y": 32,
          "width": 32
        }
      }
    },
    "number": {
      "x": 46,
      "y": 21,
      "nohit": {
        "x": 46,
        "y": 20
      },
      "perfect_game": {
        "x": 46,
        "y": 20
      }
    },
    "arrow": {
      "size": 3,
      "up": {
        "x_offset": -5,
        "y_offset": -4
      },
      "down": {
        "x_offset": -5,
        "y_offset": -2
      }
    }
  },
  "outs": {
    "1": {
      "x": 49,
      "y": 28,
      "size": 2
    },
    "2": {
      "x": 53,
      "y": 28,
      "size": 2
    },
    "3": {
      "x": 57,
      "y": 28,
      "size": 2
    }
  },
  "atbat": {
    "batter": {
      "x": 1,
      "y": 29,
      "width": 20
    },
    "pitcher": {
      "x": 1,
      "y": 21,
      "width": 24
    },
    "pitch": {
      "x": 1,
      "y": 50,
      "enabled": false,
      "mph": false,
      "desc_length": "short"
    },
    "pitch_count": {
      "x": 1,
      "y": 50,
      "enabled": false,
      "append_pitcher_name": false
    },
    "loop": 36,
    "strikeout": {
      "x": 15,
      "y": 29,
      "font_name": "5x7",
      "desc_length": "short",
      "enabled": true
    },
    "play_result": {
      "x": 15,
      "y": 29,
      "font_name": "5x7",
      "desc_length": "short",
      "enabled": true
    }
  },
  "batter_count": {
    "x": 34,
    "y": 30,
    "nohit": {
      "x": 34,
      "y": 32
    },
    "perfect_game": {
      "x": 34,
      "y": 32
    }
  },
  "nohitter": {
    "x": 34,
    "y": 26,
    "innings_until_display": 5
  },
  "pregame": {
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 64,
      "warmup": {
        "x": 0,
        "y": 31,
        "width": 64
      }
    },
    "start_time": {
      "x": 32,
      "y": 20
    },
    "warmup_text": {
      "x": 32,
      "y": 20
    }
  },
  "standings": {
    "offset": 6,
    "height": 30,
    "width": 64,
    "divider": {
      "x": 13
    },
    "stat_title": {
      "x": 28
    },
    "team": {
      "name": {
        "x": 1
      },
      "record": {
        "x": 31
      },
      "games_back": {
        "x": 64
      }
    },
    "postseason": {
      "matchup_y_gap": 6,
      "series_x_gap": 16,
      "wc_x_start": 2,
      "wc_y_start": 6,
      "ds_a_y_start": 25,
      "__comment": "all other coords are based off wild card position"
    }
  },
  "status": {
    "text": {
      "x": 32,
      "y": 20,
      "short_text": false
    },
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 64
    }
  },
  "teams": {
    "background": {
      "away": {
        "width": 64,
        "height": 7,
        "x": 0,
        "y": 0
      },
      "home": {
        "width": 64,
        "height": 7,
        "x": 0,
        "y": 7
      }
    },
    "name": {
      "away": {
        "x": 4,
        "y": 6
      },
      "home": {
        "x": 4,
        "y": 13
      },
      "full": true
    },
    "accent": {
      "away": {
        "width": 2,
        "height": 7,
        "x": 0,
        "y": 0
      },
      "home": {
        "width": 2,
        "height": 7,
        "x": 0,
        "y": 7
      }
    },
    "record": {
      "enabled": false,
      "position": "absolute",
      "away": {
        "x": 15,
        "y": 6
      },
      "home": {
        "x": 15,
        "y": 13
      },
      "hide_record_on_high_line_score": true
    },
    "line_score": {
      "away": {
        "x": 62,
        "y": 6
      },
      "home": {
        "x": 62,
        "y": 13
      },
      "show_hits_and_errors": true,
      "compress_digits": false,
      "shorten_team_name_on_high_line_score": true,
      "spacing": 3
    }
  },
  "news": {
    "scrolling_text": {
      "x": 0,
      "y": 30,
      "width": 64
    },
    "time": {
      "x": 40,
      "y": 8
    },
    "conditions": {
      "x": 40,
      "y": 16
    },
    "temperature": {
      "x": 10,
      "y": 23
    },
    "wind_speed": {
      "x": 0,
      "y": -2
    },
    "wind_dir": {
      "x": 0,
      "y": -2
    },
    "wind": {
      "x": 40,
      "y": 23
    },
    "weather_icon": {
      "x": 2,
      "y": 1,
      "width": 15,
      "height": 15
    }
  },
  "plugins": {},
  "network": {
    "font_name": "4x6",
    "background": {
      "width": 7,
      "height": 7,
      "x": 57,
      "y": 25
    },
    "text": {
      "x": 61,
      "y": 31
    }
  }
}

=== MLB-LED-Scoreboard/mlb-led-scoreboard/coordinates/w32h32.example.json
{
  "$schema": "./../schemas/coordinates/w32h32.schema.json",
  "format": 9.0,
  "defaults": {
    "font_name": "4x6"
  },
  "bases": {
    "1B": {
      "x": 24,
      "y": 24,
      "size": 6
    },
    "2B": {
      "x": 19,
      "y": 19,
      "size": 6
    },
    "3B": {
      "x": 14,
      "y": 24,
      "size": 6
    }
  },
  "final": {
    "inning": {
      "x": 16,
      "y": 20
    },
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 32
    },
    "nohit_text": {
      "x": 10,
      "y": 26
    }
  },
  "inning": {
    "break": {
      "number": {
        "x": 11,
        "y": 29
      },
      "text": {
        "x": 11,
        "y": 22
      },
      "due_up": {
        "due": {
          "x": 33,
          "y": 33
        },
        "up": {
          "x": 33,
          "y": 33
        },
        "divider": {
          "draw": false,
          "x": 33,
          "y_start": 33,
          "y_end": 33
        },
        "loop": 33,
        "leadoff": {
          "x": 33,
          "y": 33,
          "width": 0
        },
        "on_deck": {
          "x": 33,
          "y": 33,
          "width": 0
        },
        "in_hole": {
          "x": 33,
          "y": 33,
          "width": 0
        }
      }
    },
    "number": {
      "x": 32,
      "y": 20
    },
    "arrow": {
      "size": 2,
      "up": {
        "x_offset": -4,
        "y_offset": -4
      },
      "down": {
        "x_offset": -4,
        "y_offset": -3
      }
    }
  },
  "outs": {
    "1": {
      "x": 1,
      "y": 26,
      "size": 2,
      "nohit": {
        "x": 1,
        "y": 28,
        "size": 2
      },
      "perfect_game": {
        "x": 1,
        "y": 28,
        "size": 2
      }
    },
    "2": {
      "x": 5,
      "y": 26,
      "size": 2,
      "nohit": {
        "x": 5,
        "y": 28,
        "size": 2
      },
      "perfect_game": {
        "x": 5,
        "y": 28,
        "size": 2
      }
    },
    "3": {
      "x": 9,
      "y": 26,
      "size": 2,
      "nohit": {
        "x": 9,
        "y": 28,
        "size": 2
      },
      "perfect_game": {
        "x": 9,
        "y": 28,
        "size": 2
      }
    }
  },
  "atbat": {
    "batter": {
      "x": 33,
      "y": 33,
      "width": 10
    },
    "pitcher": {
      "x": 33,
      "y": 33,
      "width": 12
    },
    "pitch": {
      "font_name": "4x6",
      "x": 1,
      "y": 50,
      "enabled": false,
      "mph": false,
      "desc_length": "short"
    },
    "pitch_count": {
      "font_name": "4x6",
      "x": 1,
      "y": 50,
      "enabled": false,
      "append_pitcher_name": false
    },
    "loop": 16,
    "strikeout": {
      "x": 33,
      "y": 33,
      "desc_length": "short",
      "enabled": false
    },
    "play_result": {
      "x": 33,
      "y": 33,
      "desc_length": "short",
      "enabled": false
    }
  },
  "batter_count": {
    "x": 1,
    "y": 23,
    "nohit": {
      "x": 1,
      "y": 21
    },
    "perfect_game": {
      "x": 1,
      "y": 21
    }
  },
  "nohitter": {
    "x": 1,
    "y": 27,
    "innings_until_display": 5
  },
  "pregame": {
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 32,
      "warmup": {
        "x": 0,
        "y": 31,
        "width": 32
      }
    },
    "start_time": {
      "x": 16,
      "y": 20
    },
    "warmup_text": {
      "x": 16,
      "y": 20
    }
  },
  "standings": {
    "offset": 6,
    "height": 30,
    "width": 32,
    "divider": {
      "x": 13
    },
    "stat_title": {
      "x": 28
    },
    "team": {
      "name": {
        "x": 1
      },
      "record": {
        "x": 15
      },
      "games_back": {
        "x": 64
      }
    }
  },
  "status": {
    "text": {
      "x": 16,
      "y": 20,
      "short_text": true
    },
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 32
    }
  },
  "teams": {
    "background": {
      "away": {
        "width": 32,
        "height": 7,
        "x": 0,
        "y": 0
      },
      "home": {
        "width": 32,
        "height": 7,
        "x": 0,
        "y": 7
      }
    },
    "accent": {
      "away": {
        "width": 1,
        "height": 7,
        "x": 0,
        "y": 0
      },
      "home": {
        "width": 1,
        "height": 7,
        "x": 0,
        "y": 7
      }
    },
    "name": {
      "away": {
        "x": 3,
        "y": 6
      },
      "home": {
        "x": 3,
        "y": 13
      },
      "full": false
    },
    "record": {
      "enabled": false,
      "position": "absolute",
      "away": {
        "x": 4,
        "y": 6
      },
      "home": {
        "x": 4,
        "y": 13
      },
      "hide_record_on_high_line_score": true
    },
    "line_score": {
      "away": {
        "x": 31,
        "y": 6
      },
      "home": {
        "x": 31,
        "y": 13
      },
      "show_hits_and_errors": false,
      "compress_digits": true,
      "shorten_team_name_on_high_line_score": true,
      "spacing": 2
    }
  },
  "news": {
    "scrolling_text": {
      "x": 0,
      "y": 30,
      "width": 32
    },
    "time": {
      "x": 16,
      "y": 23
    },
    "conditions": {
      "x": 0,
      "y": -2
    },
    "temperature": {
      "x": 25,
      "y": 12
    },
    "wind_speed": {
      "x": 0,
      "y": -2
    },
    "wind_dir": {
      "x": 0,
      "y": -2
    },
    "wind": {
      "x": 0,
      "y": -2
    },
    "weather_icon": {
      "x": 1,
      "y": 1,
      "width": 15,
      "height": 15
    }
  },
  "plugins": {},
  "network": {
    "font_name": "4x6",
    "background": {
      "width": 7,
      "height": 7,
      "x": 25,
      "y": 25
    },
    "text": {
      "x": 29,
      "y": 31
    }
  }
}
